sonar.projectKey=laravel-todo2025-mael
sonar.projectName=laravel-todo2025-mael

sonar.sources=app,routes,database,resources
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/**

sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.host.url=http://192.168.0.119:9000
sonar.login=sqp_ec7832d556ef9c67b9ceaffd612dd94c0ebadfd0sqp_ec7832d556ef9c67b9ceaffd612dd94c0ebadfd0